site_name: 大明二代
site_description: 大明二代的博客
site_author: 明国宾
site_url: https://damingerdai.github.io/

theme:
  name: material
  # palette:
  #   primary: 'Blue Grey'
  #   accent: 'Pink'
  feature:
    - navigation.tabs
    - navigation.tabs.sticky
  #font:
    #text: 'Ubuntu'
    #code: 'Ubuntu Mono'
  language: 'zh'

nav:
  - 个人说明:
      - 1. 我是大明二代: index.md
  - K8S:
      - 1. Minkube安装笔记: minkube.md
  - 其他:
      - 1. 喜欢的post: link.md

copyright: copyright 2020