site_name: 大明二代
site_description: 大明二代的博客
site_author: 明国宾
site_url: https://damingerdai.github.io/

repo_name: 'damingerdai.github.io'
repo_url: 'https://github.com/damingerdai/damingerdai.github.io'

theme:
  name: material
  # palette:
  #   primary: 'Blue Grey'
  #   accent: 'Pink'
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
  font:
    text: Roboto
    code: Roboto Mono
  language: 'zh'

nav:
  - 个人说明:
      - 我是大明二代: index.md
  - 前端:
        - Angular和React构建体积简单对比: front-end/simple-comparison-of-angular-and-react-build-size.md
  - 软件:
      - docker与k8s:
        - Minkube安装笔记: k8s/how-to-install-minkube.md
        - Docker Desktop自带k8s安装笔记: k8s/how-to-install-docker-desktop-k8s.md
      - 安装笔记:
        - Android Studio安装笔记: how-to-install-android-studio.md
      
  - 其他:
      - 喜欢的post: link.md
      - 学习课程: learning.md

copyright: copyright 2021