site_name: 大明二代
site_description: 大明二代的博客
site_author: 明国宾
site_url: https://damingerdai.github.io/

repo_name: 'damingerdai.github.io'
repo_url: 'https://github.com/damingerdai/damingerdai.github.io'

theme:
  name: material
  # palette:
  #   primary: 'Blue Grey'
  #   accent: 'Pink'
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
  font:
    text: Roboto
    code: Roboto Mono
  language: 'zh'

nav:
  - 主页:
      - 我是大明二代: index.md
      - 2022年度总结: docs/summary/2022.md
  - 前端:
        - Angular和React构建体积简单对比: front-end/simple-comparison-of-angular-and-react-build-size.md
        - 在windows上构建angular项目 (上): front-end/build-angular-on-windows-01.md
        - 在windows上构建angular项目 (下): front-end/build-angular-on-windows-02.md
        - TypeScript中可选链: front-end/ts-optional-chaining.md
        - 使用Bazel编译TypeScript: front-end/build-typescript-with-bazel.md
        - Nodejs项目的Dockerfile模版: front-end/node-docker-template.md
        - 记录一次迁移Apollo Server V3的过程: front-end/log-migrate-apollo-server-v3.md
        - Angular独立组件简单体验: front-end/angular-standalone-components-app.md
  - 后端:
        - Gradle配置阿里镜像: back-end/gradle-ali-mirror.md
        - 从springfox迁移到springdoc: back-end/migrate-springdoc-from-springfox.md
        - 两种在Minikube中运行本地Docker镜像的简单方式: back-end/two-easy-ways-to-use-local-docker-images-in-minikube.md
        - 使用github action推送到docker的镜像仓库: back-end/github-action-push-docker-image-to-github-packages.md
        - 给Ingress上配置ssl证书: back-end/add-ssl-for-ingress.md
        - k3s使用Let‘s Encrypt配置https入口部署: back-end/k3s-uses-letsencrypt-and-traefik-to-deploy-the-https.md
  - 软件:
      - docker与k8s:
        - Minkube安装笔记: software/k8s/how-to-install-minkube.md
        - Docker Desktop自带k8s安装笔记: software/k8s/how-to-install-docker-desktop-k8s.md
        - Mac版minikube安装笔记: software/k8s/how-to-install-minkube-on-mac.md
        - K3S安装的时候默认使用docker: software/k8s/k3s-install-with-docker.md
      - 安装笔记:
        - Android Studio安装笔记: software/install/how-to-install-android-studio.md
        - Homebrew安装笔记: software/install/how-to-install-homebrew.md
        - drone + gogs + docker实现持续自动化部署: software/install/drone-gogs-docker-devops.md
      
  - 其他:
      - 喜欢的post: others/link.md
      - 学习课程: others/learning.md

copyright: copyright 2021